#!/bin/sh
# (c) Copyright 2008. CodeWeavers, Inc.

# Setup logging
if [ -n "$CX_LOG" ]
then
    [ "$CX_LOG" = "-" ] || exec 2>>"$CX_LOG"
    echo >&2
    echo "***** `date`" >&2
    echo "Starting: $0 $@" >&2
    set -x
fi

action="$1"
oldver="$2"

CX_ROOT="/opt/@product_id@"
CX_BOTTLE="@bottle@"
export CX_ROOT CX_BOTTLE

if [ "$action" = "configure" ]
then
    uuid=""
    uuid_file="$CX_ROOT/support/$CX_BOTTLE/.uuid"
    if [ -f "$uuid_file" ]
    then
        uuid=`cat "$uuid_file"`
        rm -f "$uuid_file"
    fi

    set_uuid=""
    if [ -n "$uuid" ]
    then
        set_uuid="--set-uuid $uuid"
    fi

    "$CX_ROOT/bin/cxbottle" $set_uuid --restored --removeall --install
fi

# Make sure the script returns 0
true

#DEBHELPER#
